version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
auth:
  htpasswd:
    realm: basic-realm
    path: /etc/registry
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
# Configuration for extensions. It follows the below schema
# extensions
#   namespace:
#     configuration for the extension and its components in any schema specific to that namespace
extensions:
  # "distribution" is the namespace
  distribution:
    # "registry" is the extension under the namespace
    registry:
      # "taghistory" & "manifests" are the components under the extension
      - taghistory
      - manifests
  # "oras" is the namespace
  oras:
    # "artifacts" is the extension under the namespace
    artifacts:
      # "referrers" is the component name.
      - referrers
